service: cowtools-rss

frameworkVersion: ">=2.24.0"

#plugins:
#  - serverless-secrets-plugin

custom:
  bucket: rss-image-cache
#  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:ListBucket 
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"
        - Effect: Allow
          Action:
            - s3:ListBucket 
          Resource: "arn:aws:s3:::${self:custom.bucket}"
functions:
  check:
    handler: handler.check
    description: generate RSS feed for Far Side comic strips
    environment:
      BUCKET: ${self:custom.bucket}
#      AWS_ACCESS_KEY_ID: ${self:custom.secrets.AWS_ACCESS_KEY_ID}
#      AWS_SECRET_ACCESS_KEY: ${self:custom.secrets.AWS_SECRET_ACCESS_KEY}
    events:
      - http:
          path: rss
          method: get
          cors: true
          integration: lambda
          response:
            headers:
              Content-Type: "'text/xml'"
            template: $input.path('$')
